import React, { useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { useMutation, useQuery } from '@tanstack/react-query';
import type { Generation } from '@video-lab/contracts';
import { generateLongFormVideo, getCredits, getRuntimeStatus, type LongFormGenerationPayload, type ReferenceRole, type StoryboardScenePayload, type StoryboardTransition } from './api.js';

type LongFormReference = { label: string; role: ReferenceRole; file?: File; preview?: string; strength: number; helper: string };

const initialReferences: LongFormReference[] = [
  { label: 'Reference image', role: 'referenceImage', strength: .6, helper: 'Guide composition, environment, props and overall visual content.' },
  { label: 'Reference character(s)', role: 'subjectReference', strength: .65, helper: 'Keep the principal character identity and appearance consistent between scenes.' },
  { label: 'Style images', role: 'styleReference', strength: .5, helper: 'Guide palette, lighting, texture and cinematography across the film.' },
];

const transitionOptions: Array<{ value: StoryboardTransition; label: string; description: string; glyph: string }> = [
  { value: 'cut', label: 'Cut', description: 'Immediate editorial cut', glyph: '┃' },
  { value: 'crossfade', label: 'Cross fade', description: 'Blend both scenes together', glyph: '◩' },
  { value: 'fade_black', label: 'Fade through black', description: 'Cinematic passage of time', glyph: '◐' },
  { value: 'fade_white', label: 'Fade through white', description: 'Bright flash transition', glyph: '◑' },
  { value: 'slide_left', label: 'Slide left', description: 'Next scene pushes left', glyph: '←' },
  { value: 'slide_right', label: 'Slide right', description: 'Next scene pushes right', glyph: '→' },
  { value: 'wipe_left', label: 'Wipe left', description: 'Hard edge sweeps left', glyph: '◧' },
  { value: 'wipe_right', label: 'Wipe right', description: 'Hard edge sweeps right', glyph: '◨' },
  { value: 'zoom_warp', label: 'Zoom warp', description: 'Fast lens push between shots', glyph: '◎' },
  { value: 'radial', label: 'Radial reveal', description: 'Circular iris transition', glyph: '◉' },
  { value: 'blur_dissolve', label: 'Blur dissolve', description: 'Soft defocus and resolve', glyph: '✣' },
];

const initialScenes: StoryboardScenePayload[] = [
  { id: 'scene-1', title: 'The signal appears', prompt: 'Wide street-level tracking shot. The founder notices a thin teal reflection moving through puddles. Keep the face and trench coat consistent; slow handheld pursuit; cool rain and warm shop windows.', duration: 8, trimStart: 0, trimEnd: 8, seed: 1337, transition: 'cut', transitionDuration: 0.75, carryPreviousFrame: true },
  { id: 'scene-2', title: 'Across the bridge', prompt: 'Begin from the previous final frame. The signal climbs a bridge rail as the camera arcs around the founder, revealing the skyline. Preserve direction of travel, identity, wet materials, and the restrained teal-and-amber palette.', duration: 8, trimStart: 0, trimEnd: 8, seed: 1338, transition: 'crossfade', transitionDuration: 0.75, carryPreviousFrame: true },
  { id: 'scene-3', title: 'The studio opens', prompt: 'The founder opens a weathered studio door. Rain falls out of focus behind them as warm practical lights take over the palette. Slow push forward and resolve on the first illuminated workstation.', duration: 8, trimStart: 0, trimEnd: 8, seed: 1339, transition: 'fade_black', transitionDuration: 0.6, carryPreviousFrame: true },
];

const initialForm: LongFormGenerationPayload = {
  overallGoal: 'A founder follows a faint teal signal through a rain-soaked London night and discovers a warm creative studio where a new product takes shape. Keep the same person, reflective trench coat, restrained teal-and-amber palette, realistic materials, and premium 35mm neo-noir cinematography throughout.',
  negativePrompt: 'low quality, blurry, jittery motion, warped anatomy, duplicated subjects, identity drift, discontinuous lighting, unreadable text, watermark, abrupt cut',
  resolution: '1280x720', fps: 24, imageSteps: 4, guidanceScale: 1, startFrameStrength: 1, endFrameStrength: .85,
  enhancePrompt: true, postProcess: 'none', outputFormat: 'mp4', seedMode: 'sequence', baseSeed: 1337,
  globalVisualAnchorEnabled: false, scenes: initialScenes,
  references: initialReferences,
};

export default function LongFormStoryboardStudio() {
  const [form, setForm] = useState(initialForm);
  const [history, setHistory] = useState<Generation[]>([]);
  const [selected, setSelected] = useState<Generation>();
  const [sceneCount, setSceneCount] = useState(6);
  const credits = useQuery({ queryKey: ['credits'], queryFn: getCredits });
  const runtime = useQuery({ queryKey: ['runtime'], queryFn: getRuntimeStatus });
  const mutation = useMutation({ mutationFn: () => generateLongFormVideo(form), onSuccess: (generation) => { setSelected(generation); setHistory((items) => [generation, ...items].slice(0, 8)); } });
  const totalSeconds = useMemo(() => form.scenes.reduce((sum, scene) => sum + Math.max(.1, scene.trimEnd - scene.trimStart), 0), [form.scenes]);
  const updateScene = (index: number, patch: Partial<StoryboardScenePayload>) => setForm((current) => ({ ...current, scenes: current.scenes.map((scene, i) => i === index ? { ...scene, ...patch } : scene) }));
  const moveScene = (index: number, direction: -1 | 1) => setForm((current) => { const target = index + direction; if (target < 0 || target >= current.scenes.length) return current; const scenes = [...current.scenes]; [scenes[index], scenes[target]] = [scenes[target], scenes[index]]; return { ...current, scenes }; });
  const addScene = () => setForm((current) => current.scenes.length >= 24 ? current : ({ ...current, scenes: [...current.scenes, { id: crypto.randomUUID(), title: `Scene ${current.scenes.length + 1}`, prompt: '', duration: 8, trimStart: 0, trimEnd: 8, seed: current.baseSeed + current.scenes.length, transition: 'crossfade', transitionDuration: .75, carryPreviousFrame: true }] }));
  const removeScene = (index: number) => setForm((current) => current.scenes.length <= 1 ? current : ({ ...current, scenes: current.scenes.filter((_, i) => i !== index) }));
  const planScenes = () => {
    const count = Math.max(1, Math.min(24, sceneCount));
    const beats = ['Opening image', 'The journey begins', 'A new obstacle', 'Discovery', 'Turning point', 'Final reveal'];
    setForm((current) => ({ ...current, scenes: Array.from({ length: count }, (_, index) => ({ id: crypto.randomUUID(), title: beats[index] ?? `Scene ${index + 1}`, prompt: `${index === 0 ? 'Establish' : 'Continue from the previous final frame and develop'} the artistic goal: ${current.overallGoal} Scene ${index + 1} of ${count}; describe one clear action, camera beat, lighting progression, and final composition.`, duration: 8, trimStart: 0, trimEnd: 8, seed: current.baseSeed + index, transition: index === 0 ? 'cut' : 'crossfade', transitionDuration: .75, carryPreviousFrame: true })) }));
  };
  const invalid = !form.overallGoal.trim() || !form.scenes.length || form.scenes.some((scene) => !scene.prompt.trim());

  return <main className="lf-page">
    <header className="lf-hero">
      <div><div className="lf-kickers"><span>Generator ready</span><span>Z-Image + LTX Storyboard</span></div><h1>LongForm LTX Storyboard Studio</h1><p>Direct a longer film scene by scene. Upload frame anchors where they matter; otherwise the runtime generates the opening and carries each real final frame into the next clip.</p></div>
      <div className="lf-session"><span>{runtime.data?.status ?? 'checking'} runtime</span><strong>{credits.data?.available ?? '…'} credits</strong><Link to="/gallery">Gallery</Link></div>
    </header>
    <div className="lf-layout"><div className="lf-controls">
      <section className="lf-panel lf-goal"><label className="lf-label">Overall artistic goal *</label><textarea value={form.overallGoal} onChange={(event) => setForm((current) => ({ ...current, overallGoal: event.target.value }))}/><p>Set the rules for the whole film. Each scene prompt should then describe one clear action and camera beat.</p><LongFormReferencePanel references={form.references as LongFormReference[]} onChange={(references) => setForm((current) => ({ ...current, references }))}/><div className="lf-plan"><label><span className="lf-label">AI scenes</span><input type="number" min={1} max={24} value={sceneCount} onChange={(event) => setSceneCount(Number(event.target.value))}/></label><button type="button" className="lf-outline" onClick={planScenes}>✣ Plan scenes</button><div className="lf-count"><strong>{form.scenes.length}/24</strong> scenes<br/><strong>{Math.floor(totalSeconds / 60)}:{String(Math.round(totalSeconds % 60)).padStart(2, '0')}</strong> requested</div></div></section>
      <section className="lf-panel lf-bible"><span className="lf-label">Film Bible</span><h2>Continuity and reproducibility</h2><p>The artistic goal is the continuity brief. A global visual anchor is an opening-frame fallback, not native style or subject conditioning.</p><div className="lf-bible-grid"><Field label="Seed strategy"><select value={form.seedMode} onChange={(event) => setForm((current) => ({ ...current, seedMode: event.target.value }))}><option value="sequence">Stable sequence</option><option value="per_scene">Per scene</option><option value="random">Random takes</option></select></Field><Field label="Base seed"><input type="number" value={form.baseSeed} onChange={(event) => setForm((current) => ({ ...current, baseSeed: Number(event.target.value) }))}/></Field><UploadBox label="Global visual anchor" compact file={form.globalVisualAnchor} onFile={(file) => setForm((current) => ({ ...current, globalVisualAnchor: file }))}/><label className="lf-toggle"><input type="checkbox" checked={form.globalVisualAnchorEnabled} onChange={(event) => setForm((current) => ({ ...current, globalVisualAnchorEnabled: event.target.checked }))}/><span/> Enable anchor fallback</label></div></section>
      <section className="lf-scenes"><div className="lf-section-head"><div><span className="lf-label">Timeline</span><h2>Storyboard scenes</h2></div><button type="button" className="lf-primary lf-add" onClick={addScene}>＋ Add scene</button></div>{form.scenes.map((scene, index) => <SceneCard key={scene.id} scene={scene} index={index} count={form.scenes.length} onChange={(patch) => updateScene(index, patch)} onMove={(direction) => moveScene(index, direction)} onRemove={() => removeScene(index)}/>)}</section>
      <section className="lf-panel lf-production"><h2>⌁ Production settings</h2><div className="lf-settings"><Field label="Working resolution"><select value={form.resolution} onChange={(event) => setForm((current) => ({ ...current, resolution: event.target.value }))}><option value="1024x576">Landscape Draft 1024x576</option><option value="1280x720">Landscape HD 1280x720</option><option value="576x1024">Phone Draft 576x1024</option><option value="720x1280">Phone HD 720x1280</option><option value="1080x1080">Square 1080x1080</option></select></Field><Field label="Frame rate"><select value={form.fps} onChange={(event) => setForm((current) => ({ ...current, fps: Number(event.target.value) }))}><option value={24}>24 fps</option><option value={25}>25 fps</option><option value={30}>30 fps</option></select></Field><Range label="Opening frame steps" value={form.imageSteps} min={1} max={12} step={1} onChange={(value) => setForm((current) => ({ ...current, imageSteps: value }))}/><Range label="LTX guidance" value={form.guidanceScale} min={0} max={8} step={.25} onChange={(value) => setForm((current) => ({ ...current, guidanceScale: value }))}/><Range label="Start frame strength" value={form.startFrameStrength} min={0} max={1} step={.05} onChange={(value) => setForm((current) => ({ ...current, startFrameStrength: value }))}/><Range label="End frame strength" value={form.endFrameStrength} min={0} max={1} step={.05} onChange={(value) => setForm((current) => ({ ...current, endFrameStrength: value }))}/><Field label="Enhance scene prompts"><select value={form.enhancePrompt ? 'yes' : 'no'} onChange={(event) => setForm((current) => ({ ...current, enhancePrompt: event.target.value === 'yes' }))}><option value="yes">Enabled</option><option value="no">Disabled</option></select></Field><Field label="Finishing pass"><select value={form.postProcess} onChange={(event) => setForm((current) => ({ ...current, postProcess: event.target.value }))}><option value="none">None - fastest draft</option><option value="interpolate">Interpolate motion</option><option value="upscale">Upscale 2x</option><option value="both">Interpolate + upscale</option></select></Field><Field label="Output format"><select value={form.outputFormat} onChange={(event) => setForm((current) => ({ ...current, outputFormat: event.target.value }))}><option value="mp4">MP4</option><option value="webm">WebM</option></select></Field></div><Field label="Shared negative prompt"><textarea className="lf-negative" value={form.negativePrompt} onChange={(event) => setForm((current) => ({ ...current, negativePrompt: event.target.value }))}/></Field><button type="button" disabled={mutation.isPending || invalid} className="lf-primary lf-generate" onClick={() => mutation.mutate()}>{mutation.isPending ? '◌ Rendering storyboard...' : 'ϟ Generate Storyboard Film'}</button>{mutation.error && <div className="lf-error">{mutation.error.message}</div>}</section>
    </div><aside className="lf-preview-col"><Preview generation={selected} loading={mutation.isPending}/><History generations={history} onSelect={setSelected}/></aside></div>
  </main>;
}

function Field({ label, children }: { label: string; children?: React.ReactNode }) { return <label className="lf-field"><span className="lf-label">{label}</span>{children}</label>; }
function Range({ label, value, min, max, step, onChange }: { label: string; value: number; min: number; max: number; step: number; onChange: (value: number) => void }) { return <Field label={label}><div className="lf-range"><input type="range" min={min} max={max} step={step} value={value} onChange={(event) => onChange(Number(event.target.value))}/><output>{value}</output></div></Field>; }

function LongFormReferencePanel({ references, onChange }: { references: LongFormReference[]; onChange: (references: LongFormReference[]) => void }) {
  const [open, setOpen] = useState(false);
  const selectedCount = references.filter((reference) => reference.file).length;
  const updateReference = (index: number, next: LongFormReference) => onChange(references.map((reference, referenceIndex) => referenceIndex === index ? next : reference));
  return <section className={`lf-reference-panel ${open ? 'open' : ''}`}>
    <button type="button" className="lf-reference-summary" aria-expanded={open} onClick={() => setOpen((value) => !value)}><span className="lf-reference-icon">▧</span><span><strong>Reference images, characters and style</strong><small>Optional visual guidance · {selectedCount ? `${selectedCount} selected` : 'collapsed'}</small></span><span className="lf-reference-chips"><i>Reference image</i><i>Character(s)</i><i>Style</i></span><b>{open ? '⌃' : '⌄'}</b></button>
    {open && <div className="lf-reference-grid">{references.map((reference, index) => <ReferenceCard key={reference.role} reference={reference} onChange={(next) => updateReference(index, next)}/>)}</div>}
  </section>;
}

function ReferenceCard({ reference, onChange }: { reference: LongFormReference; onChange: (reference: LongFormReference) => void }) {
  return <article className={`lf-reference-card ${reference.file ? 'has-file' : ''}`}><div className="lf-reference-card-head"><strong>{reference.label}</strong>{reference.file && <button type="button" onClick={() => onChange({ ...reference, file: undefined, preview: undefined })}>Remove</button>}</div><label className="lf-reference-preview">{reference.preview ? <img src={reference.preview} alt={`${reference.label} preview`}/> : <><span>▧</span><b>Upload image</b><small>PNG, JPEG or WebP</small></>}<input type="file" accept="image/png,image/jpeg,image/webp" onChange={(event) => { const file = event.target.files?.[0]; if (file) onChange({ ...reference, file, preview: URL.createObjectURL(file) }); }}/></label><p>{reference.helper}</p><label className="lf-reference-strength"><span>Strength <b>{reference.strength.toFixed(2)}</b></span><input type="range" min={0} max={1} step={.05} value={reference.strength} onChange={(event) => onChange({ ...reference, strength: Number(event.target.value) })}/></label>{reference.file && <small className="lf-reference-filename">{reference.file.name}</small>}</article>;
}

function SceneCard({ scene, index, count, onChange, onMove, onRemove }: { scene: StoryboardScenePayload; index: number; count: number; onChange: (patch: Partial<StoryboardScenePayload>) => void; onMove: (direction: -1 | 1) => void; onRemove: () => void }) {
  const [pickerOpen, setPickerOpen] = useState(false);
  const selectedTransition = transitionOptions.find((option) => option.value === scene.transition) ?? transitionOptions[0];
  return <article className="lf-scene"><header><span className="lf-scene-number">{index + 1}</span><input aria-label={`Scene ${index + 1} title`} value={scene.title} onChange={(event) => onChange({ title: event.target.value })}/><button disabled={index === 0} title="Move scene up" onClick={() => onMove(-1)}>↑</button><button disabled={index === count - 1} title="Move scene down" onClick={() => onMove(1)}>↓</button><button className="lf-delete" disabled={count <= 1} title="Remove scene" onClick={onRemove}>♲</button></header><textarea aria-label={`Scene ${index + 1} direction`} value={scene.prompt} placeholder="Subject action + camera movement + continuity + lighting progression + final composition" onChange={(event) => onChange({ prompt: event.target.value })}/><div className="lf-scene-fields"><NumberField label="Duration" value={scene.duration} min={1} max={8} step={1} onChange={(value) => onChange({ duration: value, trimEnd: Math.min(value, scene.trimEnd) })}/><NumberField label="Trim start" value={scene.trimStart} min={0} max={scene.duration - .1} step={.1} onChange={(value) => onChange({ trimStart: value })}/><NumberField label="Trim end" value={scene.trimEnd} min={.1} max={scene.duration} step={.1} onChange={(value) => onChange({ trimEnd: value })}/><NumberField label="Seed" value={scene.seed} min={0} max={999999999} step={1} onChange={(value) => onChange({ seed: value })}/>{index === 0 ? <Field label="Transition in"><div className="lf-disabled">Opening scene</div></Field> : <Field label="Transition in"><button className="lf-transition-button" onClick={() => setPickerOpen(true)}><b>{selectedTransition.glyph}</b><span>{selectedTransition.label}</span><i>›</i></button></Field>}</div><div className="lf-frames"><UploadBox label="Start frame" file={scene.startFrame} onFile={(file) => onChange({ startFrame: file })}/><UploadBox label="End frame" file={scene.endFrame} onFile={(file) => onChange({ endFrame: file })}/></div>{pickerOpen && <TransitionPicker scene={scene} onChange={onChange} onClose={() => setPickerOpen(false)}/>}</article>;
}

function NumberField({ label, value, min, max, step, onChange }: { label: string; value: number; min: number; max: number; step: number; onChange: (value: number) => void }) { return <Field label={label}><input type="number" value={value} min={min} max={max} step={step} onChange={(event) => onChange(Number(event.target.value))}/></Field>; }
function UploadBox({ label, compact = false, file, onFile }: { label: string; compact?: boolean; file?: File; onFile: (file?: File) => void }) { const [open, setOpen] = useState(false); return <div className={`lf-upload ${compact ? 'compact' : ''} ${file ? 'has-file' : ''}`}><button type="button" onClick={() => setOpen((value) => !value)}><span>▧</span>{file?.name ?? label}<i>{open ? '−' : '+'}</i></button>{open && <div className="lf-upload-body"><input type="file" accept="image/png,image/jpeg,image/webp" onChange={(event) => onFile(event.target.files?.[0])}/>{file && <button type="button" onClick={() => onFile(undefined)}>Remove</button>}</div>}</div>; }
function TransitionPicker({ scene, onChange, onClose }: { scene: StoryboardScenePayload; onChange: (patch: Partial<StoryboardScenePayload>) => void; onClose: () => void }) { return <div className="lf-modal-backdrop" role="presentation" onMouseDown={onClose}><section className="lf-transition-modal" role="dialog" aria-modal="true" aria-label="Choose transition" onMouseDown={(event) => event.stopPropagation()}><header><div><span className="lf-label">Video editor</span><h2>Choose transition</h2></div><button onClick={onClose}>×</button></header><div className="lf-transition-grid">{transitionOptions.map((option) => <button key={option.value} className={scene.transition === option.value ? 'selected' : ''} onClick={() => onChange({ transition: option.value })}><span className="lf-transition-glyph">{option.glyph}</span><strong>{option.label}</strong><small>{option.description}</small></button>)}</div><footer><div><span className="lf-label">Duration</span><strong>{scene.transition === 'cut' ? '0.00' : scene.transitionDuration.toFixed(2)}s</strong></div><input aria-label="Transition duration" type="range" min={.25} max={2} step={.05} disabled={scene.transition === 'cut'} value={scene.transitionDuration} onChange={(event) => onChange({ transitionDuration: Number(event.target.value) })}/><button className="lf-primary" onClick={onClose}>Apply</button><p>Video and audio overlap together. The final film becomes shorter by the selected transition duration.</p></footer></section></div>; }

function Preview({ generation, loading }: { generation?: Generation; loading: boolean }) { return <section className="lf-preview lf-panel"><header><div><span className="lf-label">Your creation</span><h2>Cinematic preview</h2><p>LongForm LTX Storyboard Studio</p></div><span className="lf-complete">{loading ? 'Rendering' : generation?.status ?? 'Ready'}</span></header><div className="lf-preview-tabs"><span>ϟ <b>Create</b><small>Sulphur prompt</small></span><span>▣ <b>Render</b><small>LTX video</small></span><span>♢ <b>Privacy</b><small>Private session</small></span></div><div className="lf-screen">{generation?.output?.downloadUrl ? <video src={generation.output.downloadUrl} controls/> : <img src="/images/longform-ltx-storyboard-studio-film-roll.webp" alt="Film roll containing a sequence of cinematic storyboard frames"/>}{loading && <div className="lf-rendering">Rendering storyboard film…</div>}</div>{generation?.output?.downloadUrl && <a className="lf-download" href={generation.output.downloadUrl}>⇩ Download video</a>}<p className="lf-ready">{generation ? `Generated video ${generation.status} · ${generation.creditCost} credits` : 'Your generated film will appear here'}</p><div className="lf-stats"><span><b>⌁ Progress</b>{generation?.status === 'completed' ? '100%' : loading ? 'In queue' : '—'}</span><span><b>◷ Elapsed</b>Session</span><span><b>⚙ Est. cost</b>{generation ? `${generation.creditCost} credits` : '—'}</span></div><div className="lf-progress"/></section>; }
function History({ generations, onSelect }: { generations: Generation[]; onSelect: (generation: Generation) => void }) { return <section className="lf-history lf-panel"><header><span>▣</span><div><strong>Previous generated videos</strong><small>{generations.length} previous artifacts saved in this browser</small></div><b>Open library⌄</b></header>{generations.length > 0 && <div className="lf-history-grid">{generations.map((generation) => <button key={generation.id} onClick={() => onSelect(generation)}><div>▶</div><strong>{generation.prompt}</strong><small>{generation.status} / {generation.creditCost} credits</small></button>)}</div>}</section>; }
