import React, { useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { useMutation, useQuery } from '@tanstack/react-query';
import type { Generation } from '@video-lab/contracts';
import { generateSulphurVideo, getCredits, getGeneration, getRuntimeStatus, type ReferenceRole, type SulphurGenerationPayload } from './api.js';
import { useAuthenticatedVideo } from './AuthenticatedVideo.js';

const promptModes = ['Cinematic', 'Storyboard', 'Product', 'Character'] as const;
const qualityPresets = ['draft', 'standard', 'high'] as const;
const sulphurQualityDefaults = { draft: { guidance: 3, cfgGuidance: 3, frameRate: 24 }, standard: { guidance: 5, cfgGuidance: 5, frameRate: 24 }, high: { guidance: 7, cfgGuidance: 7, frameRate: 30 } };
const previewCropAspectRatio = '16:9';
const previewCropAspectLabel = '16:9 landscape crop target';

type RefState = { label: string; role: ReferenceRole; file?: File; preview?: string; strength: number };
type FormState = {
  prompt: string; rewrittenPrompt: string; negativePrompt: string; promptMode: (typeof promptModes)[number]; quality: (typeof qualityPresets)[number]; duration: 4 | 8 | 12;
  resolution: string; aspectRatio: '16:9' | '9:16' | '1:1'; frameRate: number; seed: string; guidance: number; cfgGuidance: number; motionStrength: number; cameraMotion: string; frameInfluence: number; enhancePrompt: boolean; outputFormat: string; references: RefState[];
};

const initialReferences: RefState[] = [
  { label: 'Start Frame', role: 'startFrame', strength: 0.75 }, { label: 'End Frame', role: 'endFrame', strength: 0.75 }, { label: 'Reference Image', role: 'referenceImage', strength: 0.6 }, { label: 'Style Reference', role: 'styleReference', strength: 0.5 }, { label: 'Subject Reference', role: 'subjectReference', strength: 0.65 },
];

function initialForm(): FormState { return { prompt: 'A cinematic reveal of an intelligent glass monolith floating over an ocean at sunrise', rewrittenPrompt: '', negativePrompt: '', promptMode: 'Cinematic', quality: 'standard', duration: 4, resolution: '1280x720', aspectRatio: '16:9', frameRate: 24, seed: '', guidance: 5, cfgGuidance: 5, motionStrength: 0.55, cameraMotion: 'Slow dolly in', frameInfluence: 0.65, enhancePrompt: true, outputFormat: 'mp4', references: initialReferences }; }

export function hasSulphurGenerationInput(form: FormState) { return form.prompt.trim().length > 0 || form.references.some((ref) => ref.file); }
export function previewFileAssetId(ref: RefState) { return ref.file ? `${ref.role}:${ref.file.name}` : undefined; }
export function expandSulphurPreviewInput(form: FormState) { return { ...form, cropAspectRatio: previewCropAspectRatio, cropAspectLabel: previewCropAspectLabel }; }
export function buildSulphurPayload(form: FormState): SulphurGenerationPayload { return { prompt: (form.rewrittenPrompt || form.prompt).trim(), negativePrompt: form.negativePrompt.trim() || undefined, enhancePrompt: form.enhancePrompt, resolution: form.resolution, aspectRatio: form.aspectRatio, duration: form.duration, durationSeconds: form.duration, seed: form.seed === '' ? undefined : Number(form.seed), guidance: form.guidance, cfgGuidance: form.cfgGuidance, frameRate: form.frameRate, motionStrength: form.motionStrength, cameraMotion: form.cameraMotion, frameInfluence: form.frameInfluence, promptMode: form.promptMode, quality: form.quality, outputFormat: form.outputFormat, references: form.references.filter((ref) => ref.file).map((ref) => ({ role: ref.role, file: ref.file, strength: ref.strength })) }; }

function validate(form: FormState) { const errors: string[] = []; if (!hasSulphurGenerationInput(form)) errors.push('Add a prompt or at least one visual reference.'); const prompt = (form.rewrittenPrompt || form.prompt).trim(); if (prompt && (prompt.length < 8 || prompt.length > 1200)) errors.push('Prompt must be 8-1200 characters.'); if (![4, 8, 12].includes(form.duration)) errors.push('Duration must be 4, 8, or 12 seconds.'); if (form.seed !== '' && (!Number.isInteger(Number(form.seed)) || Number(form.seed) < 0)) errors.push('Seed must be a positive whole number.'); if (form.guidance < 0 || form.guidance > 20 || form.cfgGuidance < 0 || form.cfgGuidance > 20) errors.push('Guidance values must be between 0 and 20.'); if (!/^\d+x\d+$/.test(form.resolution)) errors.push('Resolution must look like 1280x720.'); return errors; }

export default function SulphurGeneratorPage() { const [form, setForm] = useState(initialForm); const [history, setHistory] = useState<Generation[]>([]); const [selected, setSelected] = useState<Generation | undefined>(); const validation = useMemo(() => validate(form), [form]); const credits = useQuery({ queryKey: ['credits'], queryFn: getCredits }); const runtime = useQuery({ queryKey: ['runtime'], queryFn: getRuntimeStatus }); const mutation = useMutation({ mutationFn: () => generateSulphurVideo(buildSulphurPayload(form)), onSuccess: (g) => { setSelected(g); setHistory((items) => [g, ...items].slice(0, 8)); } }); const generation = useQuery({ queryKey: ['generation', selected?.id], queryFn: () => getGeneration(selected!.id), enabled: Boolean(selected?.id), refetchInterval: (query) => { const current = query.state.data as Generation | undefined; return current && ['completed', 'failed', 'cancelled'].includes(current.status) ? false : 2000; } }); const currentGeneration = generation.data ?? selected; const isRendering = mutation.isPending || Boolean(currentGeneration && !['completed', 'failed', 'cancelled'].includes(currentGeneration.status)); return <main className="generator-page"><header className="generator-hero"><div><p className="badge">LTX Sulphur Generator</p><h1>Create a cinematic video</h1><p>Credits: {credits.data?.available ?? '…'} available · Runtime: {runtime.data?.status ?? 'checking'} · Queue {runtime.data?.queueDepth ?? '…'}</p></div><Link className="button" to="/gallery">Open gallery</Link></header><div className="studio-layout"><section className="stack"><PromptComposer form={form} setForm={setForm}/><VisualReferencePanel form={form} setForm={setForm}/><GenerationControls form={form} setForm={setForm}/>{validation.length > 0 && <div className="error-panel">{validation.map((e) => <p key={e}>{e}</p>)}</div>}<button className="button generate" disabled={isRendering || validation.length > 0} onClick={() => mutation.mutate()}>{isRendering ? 'Running on Lambda…' : 'Generate Sulphur video'}</button></section><aside className="stack"><GenerationPreview generation={currentGeneration} isLoading={isRendering} error={mutation.error}/><GenerationHistory items={history}/><pre className="preview-json">{JSON.stringify(expandSulphurPreviewInput(form), null, 2)}</pre></aside></div></main>; }

function PromptComposer({ form, setForm }: { form: FormState; setForm: React.Dispatch<React.SetStateAction<FormState>> }) { return <section className="panel"><h2>Prompt composer</h2><label>Video idea<textarea value={form.prompt} maxLength={1200} onChange={(e) => setForm((f) => ({ ...f, prompt: e.target.value }))}/></label><p>{form.prompt.length}/1200 characters</p><button disabled title="Rewrite endpoint is not exposed by this app">Rewrite Prompt unavailable</button>{form.rewrittenPrompt && <div className="callout"><strong>Rewritten prompt</strong><p>{form.rewrittenPrompt}</p></div>}<label>Negative prompt<textarea className="small-textarea" value={form.negativePrompt} onChange={(e) => setForm((f) => ({ ...f, negativePrompt: e.target.value }))}/></label><Segmented label="Prompt mode" options={promptModes} value={form.promptMode} onChange={(promptMode) => setForm((f) => ({ ...f, promptMode }))}/><Segmented label="Quality preset" options={qualityPresets} value={form.quality} onChange={(quality) => setForm((f) => ({ ...f, quality, ...sulphurQualityDefaults[quality] }))}/><label>Duration<select value={form.duration} onChange={(e) => setForm((f) => ({ ...f, duration: Number(e.target.value) as 4 | 8 | 12 }))}><option value={4}>4 seconds</option><option value={8}>8 seconds</option><option value={12}>12 seconds</option></select></label></section>; }

function Segmented<T extends string>({ label, options, value, onChange }: { label: string; options: readonly T[]; value: T; onChange: (v: T) => void }) { return <div><p>{label}</p><div className="segmented">{options.map((o) => <button key={o} className={o === value ? 'active' : ''} onClick={() => onChange(o)}>{o}</button>)}</div></div>; }
function VisualReferencePanel({ form, setForm }: { form: FormState; setForm: React.Dispatch<React.SetStateAction<FormState>> }) { const [open, setOpen] = useState(false); return <section className="panel"><header className="panel-head"><div><h2>Optional frame and identity guidance</h2>{!open && <div className="chips"><span>First / last frames optional</span><span>{previewCropAspectLabel}</span></div>}</div><button onClick={() => setOpen((v) => !v)}>{open ? 'Collapse' : 'Expand'}</button></header>{open && <div className="reference-grid">{form.references.map((ref, index) => <ReferenceUploadCard key={ref.role} refState={ref} onChange={(next) => setForm((f) => ({ ...f, references: f.references.map((r, i) => i === index ? next : r) }))}/>)}</div>}</section>; }
function ReferenceUploadCard({ refState, onChange }: { refState: RefState; onChange: (r: RefState) => void }) { return <article className="reference-card"><strong>{refState.label}</strong><div className="upload-preview">{refState.preview ? <img src={refState.preview} alt=""/> : <span>Upload image</span>}</div><input type="file" accept="image/png,image/jpeg,image/webp" onChange={(e) => { const file = e.target.files?.[0]; if (file) onChange({ ...refState, file, preview: URL.createObjectURL(file) }); }}/><label>Strength {refState.strength.toFixed(2)}<input type="range" min={0} max={1} step={0.05} value={refState.strength} onChange={(e) => onChange({ ...refState, strength: Number(e.target.value) })}/></label><small>{previewFileAssetId(refState) ?? 'No asset selected'}</small></article>; }
function GenerationControls({ form, setForm }: { form: FormState; setForm: React.Dispatch<React.SetStateAction<FormState>> }) { return <section className="panel"><h2>Advanced generation controls</h2><div className="control-grid"><label>Resolution<input value={form.resolution} onChange={(e) => setForm((f) => ({ ...f, resolution: e.target.value }))}/></label><label>Aspect ratio<select value={form.aspectRatio} onChange={(e) => setForm((f) => ({ ...f, aspectRatio: e.target.value as FormState['aspectRatio'] }))}><option>16:9</option><option>9:16</option><option>1:1</option></select></label><label>Frame rate<input type="number" value={form.frameRate} onChange={(e) => setForm((f) => ({ ...f, frameRate: Number(e.target.value) }))}/></label><label>Seed<input value={form.seed} onChange={(e) => setForm((f) => ({ ...f, seed: e.target.value }))}/><button onClick={() => setForm((f) => ({ ...f, seed: String(Math.floor(Math.random() * 2147483647)) }))}>Randomize seed</button></label><label>CFG guidance<input type="number" step="0.5" value={form.cfgGuidance} onChange={(e) => setForm((f) => ({ ...f, cfgGuidance: Number(e.target.value) }))}/></label><label>Guidance<input type="number" step="0.5" value={form.guidance} onChange={(e) => setForm((f) => ({ ...f, guidance: Number(e.target.value) }))}/></label><label>Motion strength<input type="range" min={0} max={1} step={0.05} value={form.motionStrength} onChange={(e) => setForm((f) => ({ ...f, motionStrength: Number(e.target.value) }))}/></label><label>Camera motion<input value={form.cameraMotion} onChange={(e) => setForm((f) => ({ ...f, cameraMotion: e.target.value }))}/></label><label>Frame influence<input type="range" min={0} max={1} step={0.05} value={form.frameInfluence} onChange={(e) => setForm((f) => ({ ...f, frameInfluence: Number(e.target.value) }))}/></label><label><input type="checkbox" checked={form.enhancePrompt} onChange={(e) => setForm((f) => ({ ...f, enhancePrompt: e.target.checked }))}/> Prompt enhancement</label><label>Output format<select value={form.outputFormat} onChange={(e) => setForm((f) => ({ ...f, outputFormat: e.target.value }))}><option>mp4</option><option>webm</option></select></label></div></section>; }
function GenerationPreview({ generation, isLoading, error }: { generation?: Generation; isLoading: boolean; error: Error | null }) { const video=useAuthenticatedVideo(generation?.output?.downloadUrl); return <section className="panel"><h2>Preview / result</h2>{isLoading && <div className="thumb big">Running on Lambda…</div>}{video.objectUrl ? <video className="video-preview" src={video.objectUrl} controls/> : generation?.output?.downloadUrl ? <div className="thumb big">Retrieving completed video…</div> : !isLoading && <div className="thumb big">{generation?.status ?? 'No generation yet'}</div>}{generation && <p>Status: {generation.status} · Cost: {generation.creditCost} credits</p>}{video.error && <div className="error-panel"><p>Video retrieval failed: {video.error}</p></div>}{video.objectUrl && <div className="chips"><a className="button" href={video.objectUrl} download={`${generation?.id ?? 'video'}.mp4`}>Download artifact</a><a className="button" href={video.objectUrl} target="_blank" rel="noreferrer">Open artifact</a></div>}{error && <div className="error-panel"><strong>Backend error details</strong><p>{error.message}</p></div>}</section>; }
function GenerationHistory({ items }: { items: Generation[] }) { return <section className="panel"><h2>Session history</h2>{items.length ? items.map((g) => <Link className="history-item" to={`/generations/${g.id}`} key={g.id}><strong>{g.status}</strong><span>{g.prompt}</span></Link>) : <p className="empty">Generated videos from this session will appear here.</p>}</section>; }
