/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check API health */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current user */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/credits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current credit balance */
        get: operations["getCredits"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/prompts/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Develop a prompt with the connected Sulphur runtime */
        post: operations["completePrompt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/storyboards/enhance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enhance a master prompt into an exact, structured shot sequence with local Gemma */
        post: operations["enhanceStoryboard"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/storyboards/director/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List owner-scoped Director proposals for one project */
        get: operations["listDirectorProposals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/storyboards/director/proposals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Convert a natural-language direction into a bounded reviewable proposal */
        post: operations["createDirectorProposal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/storyboards/director/proposals/{proposalId}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposalId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept an owner-scoped proposal without accepting browser-supplied mutations */
        post: operations["acceptDirectorProposal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/storyboards/director/proposals/{proposalId}/discard": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposalId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Discard an owner-scoped proposal without changing project content */
        post: operations["discardDirectorProposal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/storyboards/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the caller's private storyboard projects */
        get: operations["listStoryboardProjects"];
        put?: never;
        /** Create a private storyboard project */
        post: operations["createStoryboardProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/storyboards/projects/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        /** Reopen an owner-scoped storyboard project */
        get: operations["getStoryboardProject"];
        /** Save an owner-scoped storyboard project */
        put: operations["updateStoryboardProject"];
        post?: never;
        /** Delete the project and schedule its private assets for removal */
        delete: operations["deleteStoryboardProject"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/storyboards/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the caller's private storyboard draft */
        get: operations["getStoryboardDraft"];
        /** Save the caller's private text and settings without embedded media */
        put: operations["saveStoryboardDraft"];
        post?: never;
        /** Delete the caller's private storyboard draft */
        delete: operations["deleteStoryboardDraft"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/assets/upload-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an asset upload target */
        post: operations["createUploadUrl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/assets/{assetId}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read owner-scoped private reference bytes through Video Lab */
        get: operations["getAssetContent"];
        /** Upload image bytes through the authenticated Video Lab origin */
        put: operations["uploadAssetContent"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/generations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a video generation */
        post: operations["createGeneration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/generations/{generationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a video generation */
        get: operations["getGeneration"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/generations/{generationId}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download an owner-authorized generated image or video */
        get: operations["downloadGeneration"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/generations/{generationId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel a video generation */
        post: operations["cancelGeneration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/gallery": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List gallery generations */
        get: operations["listGallery"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runtime/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get runtime status */
        get: operations["getRuntimeStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/runtime/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pause the runtime */
        post: operations["pauseRuntime"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/runtime/discover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Force a refresh of the private Deploy Studio runtime lease */
        post: operations["discoverRuntime"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/runtime/connect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate and store an allow-listed emergency runtime origin server-side */
        post: operations["connectRuntime"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/runtime/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume the runtime */
        post: operations["resumeRuntime"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/runtime/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop the runtime */
        post: operations["stopRuntime"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/credits/adjust": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Adjust a user credit balance */
        post: operations["adjustCredits"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            ok: boolean;
            service: string;
            version: string;
        };
        PromptCompletionRequest: {
            prompt: string;
            /** @enum {string} */
            mode: "expand";
        };
        PromptCompletionResponse: {
            completedPrompt: string;
            /** @enum {string} */
            mode: "expand";
            provider: string;
        };
        /** @enum {string} */
        GenerationStatus: "queued" | "preparing" | "generating" | "uploading" | "completed" | "failed" | "cancelled";
        VideoSettings: {
            /** @enum {string} */
            aspectRatio: "16:9" | "9:16" | "1:1";
            durationSeconds: number;
            /** @enum {string} */
            quality: "draft" | "standard" | "high";
            seed?: number;
            runtime?: string;
            resolution?: string;
            overallGoal?: string;
            originalMasterPrompt?: string;
            audioPolicy?: components["schemas"]["StoryboardAudioPolicy"];
            /** @enum {string} */
            operationScope?: "project" | "scene" | "start_frame" | "end_frame" | "assembly";
            operationSceneId?: string;
            framePrompt?: string;
            /** @description Opaque Video Lab project identifier */
            projectId?: string;
            /** @enum {string} */
            seedMode?: "global_locked" | "scene_overrides";
            baseSeed?: number;
            /** @description Owner-scoped Video Lab generation identifiers; runtime job identifiers are never accepted */
            acceptedSceneGenerationIds?: string[];
            storyboard?: Record<string, never>[];
        } & {
            [key: string]: unknown;
        };
        /** @enum {string} */
        AssetPurpose: "start_frame" | "end_frame" | "reference";
        CreateUploadUrlRequest: {
            fileName: string;
            /** @enum {string} */
            contentType: "image/jpeg" | "image/png" | "image/webp";
            sizeBytes: number;
            purpose: components["schemas"]["AssetPurpose"];
        };
        CreateUploadUrlResponse: {
            assetId: string;
            uploadUrl: string;
            /** @enum {string} */
            method: "PUT";
            /** Format: date-time */
            expiresAt: string;
        };
        CreateGenerationRequest: {
            prompt: string;
            settings: components["schemas"]["VideoSettings"];
            inputAssets?: {
                assetId: string;
                purpose: components["schemas"]["AssetPurpose"];
            }[];
        };
        Generation: {
            id: string;
            prompt: string;
            settings: components["schemas"]["VideoSettings"];
            inputAssets?: Record<string, never>[];
            status: components["schemas"]["GenerationStatus"];
            queuePosition?: number;
            progress?: number;
            runtimeMessage?: string;
            runtimeProgress?: {
                framesRendered?: number;
                totalFrames?: number;
                currentScene?: number;
                totalScenes?: number;
                stage?: string;
            };
            qualityAssessment?: components["schemas"]["QualityAssessment"];
            creditCost: number;
            output?: {
                downloadUrl?: string;
                thumbnailUrl?: string;
                durationSeconds?: number;
            };
            safeErrorMessage?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        GalleryPage: {
            items: components["schemas"]["Generation"][];
            nextCursor?: string;
        };
        Me: {
            uid: string;
            email: string;
            displayName?: string;
            photoURL?: string;
            /** @enum {string} */
            status: "active" | "suspended";
            roles: string[];
            termsVersion: string;
            /** Format: date-time */
            trialGrantedAt?: string;
        };
        CreditWallet: {
            uid: string;
            available: number;
            reserved: number;
            spent: number;
            /** Format: date-time */
            updatedAt: string;
            version: number;
        };
        RuntimeDiscovery: {
            /** @enum {string} */
            source: "deploy-studio" | "environment" | "legacy" | "none";
            /** @enum {string} */
            state: "connected" | "waiting" | "stale" | "unavailable";
            /** Format: date-time */
            leaseExpiresAt?: string;
            /** Format: date-time */
            lastPublishedAt?: string;
            message?: string;
        };
        StoryboardContinuityBible: {
            characters: string;
            wardrobe: string;
            props: string;
            location: string;
            sceneGeometry: string;
            timeOfDay: string;
            lighting: string;
            palette: string;
            lens: string;
            cameraPosition: string;
            cameraMovement: string;
            visualStyle: string;
            audio: string;
        };
        StoryboardEnhancementShotInput: {
            shotNumber: number;
            title: string;
            narrativePurpose: string;
            prompt: string;
            firstFramePrompt: string;
            lastFramePrompt: string;
            continuityNotes: string;
            durationSeconds: number;
            /** @enum {string} */
            generationMode: "text_to_video" | "image_to_video" | "mixed";
            referenceIds: string[];
            selectedControls: string[];
            audioIntent: components["schemas"]["StoryboardAudioIntent"];
            carryPreviousFrame: boolean;
            firstFrameAvailable: boolean;
            lastFrameAvailable: boolean;
        };
        StoryboardReferenceSummary: {
            id: string;
            /** @enum {string} */
            type: "character" | "location" | "product" | "style" | "voice" | "motion";
            label: string;
            description: string;
            lockedTraits: string[];
            version: number;
            shotNumbers: number[];
        };
        StoryboardAudioPolicy: {
            /** @enum {string} */
            mode: "silent" | "intent_only" | "directed";
            /** @enum {string} */
            dialogue: "off" | "prompted_only" | "on";
            /** @enum {string} */
            soundEffects: "off" | "intent_only" | "on";
            /** @enum {string} */
            ambience: "off" | "intent_only" | "on";
            /** @enum {string} */
            music: "off" | "prompted_or_unambiguous_performance" | "on";
            preserveSourceAudio: boolean;
        };
        StoryboardAudioIntent: {
            /** @enum {string} */
            mode: "silent" | "dialogue" | "ambience" | "sound_effects" | "music" | "mixed";
            reason: string;
        };
        StoryboardReferenceUsage: {
            referenceId: string;
            shotNumbers: number[];
            purpose: string;
        };
        InstructionBundle: {
            directorVersion: string;
            enhancerVersion: string;
            framePromptVersion: string;
            hash: string;
        };
        QualityAssessment: {
            version: string;
            /** @enum {boolean} */
            advisory: true;
            score: number;
            /** @enum {string} */
            recommendation: "review" | "recommended" | "repair";
            checks: {
                id: string;
                /** @enum {string} */
                status: "passed" | "failed" | "warning" | "not_evaluated";
                confidence: number;
                detail?: string;
            }[];
        };
        StoryboardEnhancementRequest: {
            /** @constant */
            contractVersion: "2";
            /** @enum {string} */
            operation: "enhance_master_prompt" | "plan_storyboard" | "revise_shot" | "revise_first_frame" | "revise_last_frame";
            userInstruction?: string;
            masterPrompt: string;
            shotCount: number;
            /** @enum {string} */
            generationMode: "text_to_video" | "image_to_video" | "mixed";
            continuityBible: components["schemas"]["StoryboardContinuityBible"];
            shots: components["schemas"]["StoryboardEnhancementShotInput"][];
            targetShotNumber?: number;
            projectId?: string;
            projectRevision?: string;
            /** @enum {string} */
            aspectRatio: "16:9" | "9:16" | "1:1";
            resolution: string;
            references: components["schemas"]["StoryboardReferenceSummary"][];
            availableControls: string[];
            audioPolicy: components["schemas"]["StoryboardAudioPolicy"];
            requestedCandidateCount: number;
        };
        EnhancedStoryboardShot: {
            shotNumber: number;
            title: string;
            narrativePurpose: string;
            prompt: string;
            firstFramePrompt: string;
            lastFramePrompt: string;
            continuityNotes: string;
            referenceIds: string[];
            recommendedControls: string[];
            audioIntent: components["schemas"]["StoryboardAudioIntent"];
            candidateVariations: string[];
        };
        StoryboardEnhancementResponse: {
            /** @constant */
            contractVersion: "2";
            polishedMasterPrompt: string;
            continuityBible: components["schemas"]["StoryboardContinuityBible"];
            referenceUsagePlan: components["schemas"]["StoryboardReferenceUsage"][];
            assumptions: string[];
            shots: components["schemas"]["EnhancedStoryboardShot"][];
            /** @enum {string} */
            provider: "ollama" | "mock";
            model: string;
            instructionBundle: components["schemas"]["InstructionBundle"];
        };
        /** @enum {string} */
        DirectorActionType: "answer_project_question" | "suggest_creative_direction" | "enhance_master_prompt" | "plan_storyboard" | "propose_scene_change" | "propose_frame_prompt_change" | "restore_original_prompt" | "undo_prompt_change" | "assign_project_reference" | "remove_project_reference" | "set_audio_policy" | "generate_first_frame" | "generate_last_frame" | "regenerate_frame" | "restore_frame_version" | "generate_scene_candidates" | "accept_candidate" | "restore_candidate" | "generate_scene_video" | "generate_unfinished_scenes" | "cancel_job" | "retry_job" | "explain_failure" | "prepare_finishing" | "assemble_project" | "export_project";
        DirectorProposalDiff: {
            path: string;
            label: string;
            before?: string;
            after?: string;
        };
        DirectorProposalRequest: {
            projectId: string;
            message: string;
            selectedSceneId?: string;
        };
        DirectorProposal: {
            id: string;
            projectId: string;
            /** Format: date-time */
            projectRevision: string;
            /** @enum {string} */
            kind: "answer" | "suggestion" | "draft_change" | "action_request";
            action: components["schemas"]["DirectorActionType"];
            /** @enum {string} */
            state: "pending" | "accepted" | "discarded";
            summary: string;
            explanation: string;
            confirmationRequired: boolean;
            /** @enum {string} */
            executionClass: "none" | "text" | "draft" | "final";
            affectedSceneIds: string[];
            preserve: string[];
            invalidations: string[];
            diff: components["schemas"]["DirectorProposalDiff"][];
            payload: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        DirectorProposalResult: {
            proposal: components["schemas"]["DirectorProposal"];
            project?: components["schemas"]["StoryboardProject"];
        };
        StoryboardProjectSummary: {
            id: string;
            title: string;
            sceneCount: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        StoryboardProject: components["schemas"]["StoryboardProjectSummary"] & {
            form: {
                [key: string]: unknown;
            };
        };
        StoryboardProjectWrite: {
            title: string;
            form: {
                [key: string]: unknown;
            };
        };
        RuntimeCapabilities: {
            maxScenes: number;
            maxSceneDurationSeconds: number;
            workflowModes: ("text" | "start" | "start_end")[];
            operationScopes: ("project" | "scene" | "start_frame" | "end_frame" | "assembly")[];
            postProcess: ("none" | "interpolate" | "upscale" | "both")[];
            startFrame: boolean;
            endFrame: boolean;
            generatedOpeningFrame: boolean;
            previousFrameContinuity: boolean;
            sceneAssembly: boolean;
            audioPreservation: boolean;
            styleReference: boolean;
            subjectReference: boolean;
            audioPolicyModes?: ("silent" | "intent_only" | "directed")[];
            /** @enum {string|null} */
            enhancementContractVersion?: "2" | null;
            featureStatus?: {
                [key: string]: "supported" | "partial" | "unavailable" | "client_managed";
            };
            instructionBundle?: components["schemas"]["InstructionBundle"];
        };
        RuntimeStatus: {
            provider: string;
            /** @enum {string} */
            status: "healthy" | "degraded" | "unavailable" | "paused";
            acceptingSubmissions: boolean;
            killSwitch: boolean;
            /** Format: date-time */
            lastHeartbeatAt?: string;
            activeGenerationId?: string;
            queueDepth: number;
            /** Format: date-time */
            updatedAt: string;
            discovery?: components["schemas"]["RuntimeDiscovery"];
            capabilities?: components["schemas"]["RuntimeCapabilities"];
        };
        AdminCreditAdjustment: {
            uid: string;
            amount: number;
            reason: string;
        };
        Problem: {
            type: string;
            title: string;
            status: number;
            detail: string;
            code: string;
            traceId: string;
            fieldErrors?: Record<string, never>[];
        };
    };
    responses: {
        /** @description Request validation failed */
        InvalidRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Authentication is missing, invalid or expired */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The authenticated caller is not authorized for this operation */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The resource does not exist or is not owned by the caller */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Request rate limit exceeded */
        RateLimited: {
            headers: {
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        generationId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Me */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getCredits: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Credits */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreditWallet"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    completePrompt: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PromptCompletionRequest"];
            };
        };
        responses: {
            /** @description Completed prompt */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptCompletionResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Runtime unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    enhanceStoryboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoryboardEnhancementRequest"];
            };
        };
        responses: {
            /** @description Validated storyboard enhancement */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoryboardEnhancementResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Local enhancer unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listDirectorProposals: {
        parameters: {
            query: {
                projectId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project Director history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["DirectorProposal"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Project not found or not owned by caller */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createDirectorProposal: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DirectorProposalRequest"];
            };
        };
        responses: {
            /** @description Validated Director proposal */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DirectorProposal"];
                };
            };
            /** @description Invalid or unsupported Director request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            /** @description Local Director unavailable for creative rewriting */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    acceptDirectorProposal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposalId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted proposal and any updated project */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DirectorProposalResult"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Proposal or project not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Proposal resolved or project revision changed */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    discardDirectorProposal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposalId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Discarded proposal */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DirectorProposal"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Proposal not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Proposal already resolved */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listStoryboardProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Owner-scoped project summaries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["StoryboardProjectSummary"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createStoryboardProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoryboardProjectWrite"];
            };
        };
        responses: {
            /** @description Created project */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoryboardProject"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getStoryboardProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Private project */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoryboardProject"];
                };
            };
            /** @description Project not found or not owned by caller */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateStoryboardProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoryboardProjectWrite"];
            };
        };
        responses: {
            /** @description Saved project */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoryboardProject"];
                };
            };
            /** @description Project not found or not owned by caller */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteStoryboardProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project deletion scheduled */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Project not found or not owned by caller */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getStoryboardDraft: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Private draft */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    saveStoryboardDraft: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    form: Record<string, never>;
                };
            };
        };
        responses: {
            /** @description Saved private draft */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    deleteStoryboardDraft: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createUploadUrl: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUploadUrlRequest"];
            };
        };
        responses: {
            /** @description Upload target */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateUploadUrlResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getAssetContent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assetId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Private image bytes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": string;
                    "image/png": string;
                    "image/webp": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Asset not found or not owned by caller */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    uploadAssetContent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assetId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "image/jpeg": string;
                "image/png": string;
                "image/webp": string;
            };
        };
        responses: {
            /** @description Uploaded */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createGeneration: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGenerationRequest"];
            };
        };
        responses: {
            /** @description Idempotent replay */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Generation"];
                };
            };
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Generation"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getGeneration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                generationId: components["parameters"]["generationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Generation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Generation"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    downloadGeneration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                generationId: components["parameters"]["generationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Generated media */
            200: {
                headers: {
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "video/mp4": string;
                    "video/webm": string;
                    "image/png": string;
                    "image/jpeg": string;
                    "image/webp": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    cancelGeneration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                generationId: components["parameters"]["generationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancelled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Generation"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listGallery: {
        parameters: {
            query?: {
                cursor?: string;
                status?: components["schemas"]["GenerationStatus"];
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Gallery */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GalleryPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getRuntimeStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Runtime */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeStatus"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    pauseRuntime: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Runtime */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeStatus"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    discoverRuntime: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Runtime discovery refreshed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeStatus"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    connectRuntime: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uri */
                    baseUrl: string;
                };
            };
        };
        responses: {
            /** @description Runtime connection established; the configured origin is not returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeStatus"];
                };
            };
            400: components["responses"]["InvalidRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Runtime health check failed */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    resumeRuntime: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Runtime */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeStatus"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    stopRuntime: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Runtime */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeStatus"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    adjustCredits: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminCreditAdjustment"];
            };
        };
        responses: {
            /** @description Credits */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreditWallet"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
}
