/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check API health */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current user */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/credits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current credit balance */
        get: operations["getCredits"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/assets/upload-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an asset upload target */
        post: operations["createUploadUrl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/generations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a video generation */
        post: operations["createGeneration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/generations/{generationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a video generation */
        get: operations["getGeneration"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/generations/{generationId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel a video generation */
        post: operations["cancelGeneration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/gallery": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List gallery generations */
        get: operations["listGallery"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runtime/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get runtime status */
        get: operations["getRuntimeStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/runtime/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pause the runtime */
        post: operations["pauseRuntime"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/runtime/connect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["connectRuntime"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/runtime/release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Release the connected runtime so a replacement endpoint can be configured */
        post: operations["releaseRuntime"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/runtime/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume the runtime */
        post: operations["resumeRuntime"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/runtime/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop the runtime */
        post: operations["stopRuntime"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/credits/adjust": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Adjust a user credit balance */
        post: operations["adjustCredits"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            ok: boolean;
            service: string;
            version: string;
        };
        RuntimeHealth: {
            ok: boolean;
            provider: string;
            worker?: string;
            ready?: boolean;
            message?: string;
        };
        RuntimeConnectRequest: {
            lambdaIp?: string;
            baseUrl?: string;
        };
        RuntimeConnectResponse: components["schemas"]["RuntimeStatus"] & {
            baseUrl: string;
            health?: components["schemas"]["RuntimeHealth"];
        };
        /** @enum {string} */
        GenerationStatus: "queued" | "preparing" | "generating" | "uploading" | "completed" | "failed" | "cancelled";
        VideoSettings: {
            /** @enum {string} */
            aspectRatio: "16:9" | "9:16" | "1:1";
            durationSeconds: number;
            /** @enum {string} */
            quality: "draft" | "standard" | "high";
            seed?: number;
            runtime?: string;
            resolution?: string;
            overallGoal?: string;
            storyboard?: Record<string, never>[];
        } & {
            [key: string]: unknown;
        };
        /** @enum {string} */
        AssetPurpose: "start_frame" | "end_frame" | "reference";
        CreateUploadUrlRequest: {
            fileName: string;
            /** @enum {string} */
            contentType: "image/jpeg" | "image/png" | "image/webp";
            sizeBytes: number;
            purpose: components["schemas"]["AssetPurpose"];
        };
        CreateUploadUrlResponse: {
            assetId: string;
            uploadUrl: string;
            /** @enum {string} */
            method: "PUT";
            /** Format: date-time */
            expiresAt: string;
            objectPath: string;
        };
        CreateGenerationRequest: {
            prompt: string;
            settings: components["schemas"]["VideoSettings"];
            inputAssets?: {
                assetId: string;
                purpose: components["schemas"]["AssetPurpose"];
            }[];
        };
        Generation: {
            id: string;
            prompt: string;
            settings: components["schemas"]["VideoSettings"];
            inputAssets?: Record<string, never>[];
            status: components["schemas"]["GenerationStatus"];
            queuePosition?: number;
            creditCost: number;
            output?: {
                downloadUrl?: string;
                thumbnailUrl?: string;
                durationSeconds?: number;
            };
            safeErrorMessage?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        GalleryPage: {
            items: components["schemas"]["Generation"][];
            nextCursor?: string;
        };
        Me: {
            uid: string;
            email: string;
            displayName?: string;
            photoURL?: string;
            /** @enum {string} */
            status: "active" | "suspended";
            roles: string[];
            termsVersion: string;
            /** Format: date-time */
            trialGrantedAt?: string;
        };
        CreditWallet: {
            uid: string;
            available: number;
            reserved: number;
            spent: number;
            /** Format: date-time */
            updatedAt: string;
            version: number;
        };
        RuntimeStatus: {
            provider: string;
            /** @enum {string} */
            status: "healthy" | "degraded" | "unavailable" | "paused";
            acceptingSubmissions: boolean;
            killSwitch: boolean;
            /** Format: date-time */
            lastHeartbeatAt?: string;
            activeGenerationId?: string;
            queueDepth: number;
            /** Format: date-time */
            updatedAt: string;
            baseUrl?: string;
        };
        AdminCreditAdjustment: {
            uid: string;
            amount: number;
            reason: string;
        };
        Problem: {
            type: string;
            title: string;
            status: number;
            detail: string;
            code: string;
            traceId: string;
            fieldErrors?: Record<string, never>[];
        };
    };
    responses: never;
    parameters: {
        generationId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Me */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    getCredits: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Credits */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreditWallet"];
                };
            };
        };
    };
    createUploadUrl: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUploadUrlRequest"];
            };
        };
        responses: {
            /** @description Upload target */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateUploadUrlResponse"];
                };
            };
        };
    };
    createGeneration: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGenerationRequest"];
            };
        };
        responses: {
            /** @description Idempotent replay */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Generation"];
                };
            };
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Generation"];
                };
            };
        };
    };
    getGeneration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                generationId: components["parameters"]["generationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Generation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Generation"];
                };
            };
        };
    };
    cancelGeneration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                generationId: components["parameters"]["generationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancelled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Generation"];
                };
            };
        };
    };
    listGallery: {
        parameters: {
            query?: {
                cursor?: string;
                status?: components["schemas"]["GenerationStatus"];
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Gallery */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GalleryPage"];
                };
            };
        };
    };
    getRuntimeStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Runtime */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeStatus"];
                };
            };
        };
    };
    pauseRuntime: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Runtime */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeStatus"];
                };
            };
        };
    };
    connectRuntime: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuntimeConnectRequest"];
            };
        };
        responses: {
            /** @description Runtime connected */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeConnectResponse"];
                };
            };
        };
    };
    releaseRuntime: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Runtime released */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeStatus"];
                };
            };
            /** @description Runtime has an active generation */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    resumeRuntime: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Runtime */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeStatus"];
                };
            };
        };
    };
    stopRuntime: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Runtime */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeStatus"];
                };
            };
        };
    };
    adjustCredits: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminCreditAdjustment"];
            };
        };
        responses: {
            /** @description Credits */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreditWallet"];
                };
            };
        };
    };
}
