/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check API health */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current user */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/credits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current credit balance */
        get: operations["getCredits"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/prompts/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Develop a prompt with the connected Sulphur runtime */
        post: operations["completePrompt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/storyboards/enhance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enhance a master prompt into an exact, structured shot sequence with local Gemma */
        post: operations["enhanceStoryboard"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/storyboards/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the caller's private storyboard draft */
        get: operations["getStoryboardDraft"];
        /** Save the caller's private text and settings without embedded media */
        put: operations["saveStoryboardDraft"];
        post?: never;
        /** Delete the caller's private storyboard draft */
        delete: operations["deleteStoryboardDraft"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/assets/upload-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an asset upload target */
        post: operations["createUploadUrl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/assets/{assetId}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Upload image bytes through the authenticated Video Lab origin */
        put: operations["uploadAssetContent"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/generations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a video generation */
        post: operations["createGeneration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/generations/{generationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a video generation */
        get: operations["getGeneration"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/generations/{generationId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel a video generation */
        post: operations["cancelGeneration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/gallery": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List gallery generations */
        get: operations["listGallery"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runtime/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get runtime status */
        get: operations["getRuntimeStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/runtime/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pause the runtime */
        post: operations["pauseRuntime"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/runtime/discover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Force a refresh of the private Deploy Studio runtime lease */
        post: operations["discoverRuntime"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/runtime/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume the runtime */
        post: operations["resumeRuntime"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/runtime/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop the runtime */
        post: operations["stopRuntime"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/credits/adjust": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Adjust a user credit balance */
        post: operations["adjustCredits"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            ok: boolean;
            service: string;
            version: string;
        };
        RuntimeHealth: {
            ok: boolean;
            provider: string;
            worker?: string;
            ready?: boolean;
            message?: string;
        };
        PromptCompletionRequest: {
            prompt: string;
            /** @enum {string} */
            mode: "expand";
        };
        PromptCompletionResponse: {
            completedPrompt: string;
            /** @enum {string} */
            mode: "expand";
            provider: string;
        };
        /** @enum {string} */
        GenerationStatus: "queued" | "preparing" | "generating" | "uploading" | "completed" | "failed" | "cancelled";
        VideoSettings: {
            /** @enum {string} */
            aspectRatio: "16:9" | "9:16" | "1:1";
            durationSeconds: number;
            /** @enum {string} */
            quality: "draft" | "standard" | "high";
            seed?: number;
            runtime?: string;
            resolution?: string;
            overallGoal?: string;
            /** @enum {string} */
            operationScope?: "project" | "scene" | "start_frame" | "end_frame" | "assembly";
            operationSceneId?: string;
            framePrompt?: string;
            storyboard?: Record<string, never>[];
        } & {
            [key: string]: unknown;
        };
        /** @enum {string} */
        AssetPurpose: "start_frame" | "end_frame" | "reference";
        CreateUploadUrlRequest: {
            fileName: string;
            /** @enum {string} */
            contentType: "image/jpeg" | "image/png" | "image/webp";
            sizeBytes: number;
            purpose: components["schemas"]["AssetPurpose"];
        };
        CreateUploadUrlResponse: {
            assetId: string;
            uploadUrl: string;
            /** @enum {string} */
            method: "PUT";
            /** Format: date-time */
            expiresAt: string;
        };
        CreateGenerationRequest: {
            prompt: string;
            settings: components["schemas"]["VideoSettings"];
            inputAssets?: {
                assetId: string;
                purpose: components["schemas"]["AssetPurpose"];
            }[];
        };
        Generation: {
            id: string;
            prompt: string;
            settings: components["schemas"]["VideoSettings"];
            inputAssets?: Record<string, never>[];
            status: components["schemas"]["GenerationStatus"];
            queuePosition?: number;
            progress?: number;
            runtimeMessage?: string;
            creditCost: number;
            output?: {
                downloadUrl?: string;
                thumbnailUrl?: string;
                durationSeconds?: number;
            };
            safeErrorMessage?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        GalleryPage: {
            items: components["schemas"]["Generation"][];
            nextCursor?: string;
        };
        Me: {
            uid: string;
            email: string;
            displayName?: string;
            photoURL?: string;
            /** @enum {string} */
            status: "active" | "suspended";
            roles: string[];
            termsVersion: string;
            /** Format: date-time */
            trialGrantedAt?: string;
        };
        CreditWallet: {
            uid: string;
            available: number;
            reserved: number;
            spent: number;
            /** Format: date-time */
            updatedAt: string;
            version: number;
        };
        RuntimeDiscovery: {
            /** @enum {string} */
            source: "deploy-studio" | "environment" | "legacy" | "none";
            /** @enum {string} */
            state: "connected" | "waiting" | "stale" | "unavailable";
            /** Format: date-time */
            leaseExpiresAt?: string;
            /** Format: date-time */
            lastPublishedAt?: string;
            message?: string;
        };
        StoryboardContinuityBible: {
            characters: string;
            wardrobe: string;
            props: string;
            location: string;
            sceneGeometry: string;
            timeOfDay: string;
            lighting: string;
            palette: string;
            lens: string;
            cameraPosition: string;
            cameraMovement: string;
            visualStyle: string;
            audio: string;
        };
        StoryboardEnhancementShotInput: {
            shotNumber: number;
            title: string;
            prompt: string;
            durationSeconds: number;
            /** @enum {string} */
            generationMode: "text_to_video" | "image_to_video" | "mixed";
        };
        StoryboardEnhancementRequest: {
            masterPrompt: string;
            shotCount: number;
            /** @enum {string} */
            generationMode: "text_to_video" | "image_to_video" | "mixed";
            continuityBible: components["schemas"]["StoryboardContinuityBible"];
            shots: components["schemas"]["StoryboardEnhancementShotInput"][];
            targetShotNumber?: number;
        };
        EnhancedStoryboardShot: {
            shotNumber: number;
            title: string;
            narrativePurpose: string;
            prompt: string;
            firstFramePrompt: string;
            lastFramePrompt: string;
            continuityNotes: string;
        };
        StoryboardEnhancementResponse: {
            polishedMasterPrompt: string;
            continuityBible: components["schemas"]["StoryboardContinuityBible"];
            shots: components["schemas"]["EnhancedStoryboardShot"][];
            /** @enum {string} */
            provider: "ollama" | "mock";
            model: string;
        };
        RuntimeStatus: {
            provider: string;
            /** @enum {string} */
            status: "healthy" | "degraded" | "unavailable" | "paused";
            acceptingSubmissions: boolean;
            killSwitch: boolean;
            /** Format: date-time */
            lastHeartbeatAt?: string;
            activeGenerationId?: string;
            queueDepth: number;
            /** Format: date-time */
            updatedAt: string;
            discovery?: components["schemas"]["RuntimeDiscovery"];
        };
        AdminCreditAdjustment: {
            uid: string;
            amount: number;
            reason: string;
        };
        Problem: {
            type: string;
            title: string;
            status: number;
            detail: string;
            code: string;
            traceId: string;
            fieldErrors?: Record<string, never>[];
        };
    };
    responses: never;
    parameters: {
        generationId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Me */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    getCredits: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Credits */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreditWallet"];
                };
            };
        };
    };
    completePrompt: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PromptCompletionRequest"];
            };
        };
        responses: {
            /** @description Completed prompt */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptCompletionResponse"];
                };
            };
            /** @description Runtime unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    enhanceStoryboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoryboardEnhancementRequest"];
            };
        };
        responses: {
            /** @description Validated storyboard enhancement */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoryboardEnhancementResponse"];
                };
            };
            /** @description Local enhancer unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getStoryboardDraft: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Private draft */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    saveStoryboardDraft: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    form: Record<string, never>;
                };
            };
        };
        responses: {
            /** @description Saved private draft */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteStoryboardDraft: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createUploadUrl: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUploadUrlRequest"];
            };
        };
        responses: {
            /** @description Upload target */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateUploadUrlResponse"];
                };
            };
        };
    };
    uploadAssetContent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assetId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "image/jpeg": string;
                "image/png": string;
                "image/webp": string;
            };
        };
        responses: {
            /** @description Uploaded */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createGeneration: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGenerationRequest"];
            };
        };
        responses: {
            /** @description Idempotent replay */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Generation"];
                };
            };
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Generation"];
                };
            };
        };
    };
    getGeneration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                generationId: components["parameters"]["generationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Generation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Generation"];
                };
            };
        };
    };
    cancelGeneration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                generationId: components["parameters"]["generationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancelled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Generation"];
                };
            };
        };
    };
    listGallery: {
        parameters: {
            query?: {
                cursor?: string;
                status?: components["schemas"]["GenerationStatus"];
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Gallery */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GalleryPage"];
                };
            };
        };
    };
    getRuntimeStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Runtime */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeStatus"];
                };
            };
        };
    };
    pauseRuntime: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Runtime */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeStatus"];
                };
            };
        };
    };
    discoverRuntime: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Runtime discovery refreshed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeStatus"];
                };
            };
        };
    };
    resumeRuntime: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Runtime */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeStatus"];
                };
            };
        };
    };
    stopRuntime: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Runtime */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeStatus"];
                };
            };
        };
    };
    adjustCredits: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminCreditAdjustment"];
            };
        };
        responses: {
            /** @description Credits */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreditWallet"];
                };
            };
        };
    };
}
