import express from 'express';import cors from 'cors';import swaggerUi from 'swagger-ui-express';import fs from 'node:fs';import YAML from 'yaml';import { nanoid } from 'nanoid';import type { CreditWallet, Generation, Me, RuntimeStatus } from '@video-lab/contracts';import { calculateCreditCost, chargeCredits, claimNext, createWallet, releaseCredits, reserveCredits, type QueueItem } from '@video-lab/domain';import { createRuntimeFromEnv } from '@video-lab/runtime-adapter';import { log, nowIso, problem } from '@video-lab/shared';
type Principal={uid:string;email:string;admin:boolean}; const runtime=createRuntimeFromEnv();
const users=new Map<string,Me>(); const wallets=new Map<string,CreditWallet>(); const gens=new Map<string,Generation&{uid:string;runtimeJobId?:string}>(); const queue:QueueItem[]=[]; const idempotency=new Map<string,string>(); const assets=new Map<string,{uid:string;purpose:string;objectPath:string;uploaded:boolean}>(); let runtimeState:RuntimeStatus={provider:process.env.VIDEO_RUNTIME_PROVIDER??'mock',status:'healthy',acceptingSubmissions:true,killSwitch:false,queueDepth:0,updatedAt:nowIso(),lastHeartbeatAt:nowIso()};
const allowDevAuthShortcuts=process.env.NODE_ENV!=='production'&&process.env.ALLOW_DEV_AUTH_SHORTCUTS!=='false';
function principal(req:express.Request):Principal{ const cookieToken=req.cookies?.vl_session as string|undefined; if(cookieToken){ const [uid,email,adminFlag]=cookieToken.split('|'); if(uid&&email) return {uid,email,admin:adminFlag==='1'}; } const h=req.header('authorization'); if(!h?.startsWith('Bearer ')) throw problem(401,'unauthenticated','Missing Firebase bearer token'); const token=h.slice(7); if(allowDevAuthShortcuts&&token==='admin-token') return {uid:'admin',email:'admin@example.test',admin:true}; if(allowDevAuthShortcuts) return {uid:token.replace(/[^a-zA-Z0-9_-]/g,'').slice(0,64)||'demo',email:`${token}@example.test`,admin:false}; throw problem(401,'unauthenticated','Development auth shortcuts are disabled');}
function ensureUser(p:Principal){ let u=users.get(p.uid); if(!u){u={uid:p.uid,email:p.email,status:'active',roles:p.admin?['admin']:[],termsVersion:'2026-07',trialGrantedAt:nowIso()}; users.set(p.uid,u); wallets.set(p.uid,createWallet(p.uid,Number(process.env.FREE_TRIAL_CREDITS??12))); log('trial_credit_granted',{uid:p.uid});} return u;}
function auth(req:express.Request,res:express.Response,next:express.NextFunction){try{const p=principal(req); ensureUser(p); res.locals.principal=p; next();}catch(e){next(e)}}
function admin(req:express.Request,res:express.Response,next:express.NextFunction){try{const p=principal(req); ensureUser(p); if(!p.admin) throw problem(403,'admin_required','Admin custom claim required'); res.locals.principal=p; next();}catch(e){next(e)}}
export const app=express(); app.use(cors({origin:true,credentials:true})); app.use(express.json({limit:'1mb'}));
app.use((req,_res,next)=>{ const cookieHeader=req.header('cookie')??''; req.cookies=Object.fromEntries(cookieHeader.split(';').map((c)=>c.trim()).filter(Boolean).map((pair)=>{ const idx=pair.indexOf('='); return idx>0?[decodeURIComponent(pair.slice(0,idx)),decodeURIComponent(pair.slice(idx+1))]:[pair,'']; })); next(); });
if(process.env.NODE_ENV!=='production'){ const doc=YAML.parse(fs.readFileSync(new URL('../../../contracts/video-lab.openapi.yaml',import.meta.url),'utf8')); app.use('/docs',swaggerUi.serve,swaggerUi.setup(doc));}
app.get('/v1/health',(_req,res)=>res.json({ok:true,service:'video-lab-api',version:'0.1.0'}));
app.get('/v1/me',auth,(req,res)=>res.json(users.get(res.locals.principal.uid)));
app.get('/v1/credits',auth,(req,res)=>res.json(wallets.get(res.locals.principal.uid)));
app.post('/v1/session/bootstrap',auth,(req,res)=>{ const p=res.locals.principal as Principal; const value=encodeURIComponent(`${p.uid}|${p.email}|${p.admin?'1':'0'}`); res.cookie('vl_session',value,{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',path:'/',maxAge:7*24*60*60_000}); res.json({ok:true}); });
function uploadBaseUrl(){ const emu=process.env.FIREBASE_STORAGE_EMULATOR_HOST; if(emu) return `http://${emu}`; if(process.env.UPLOAD_BASE_URL) return process.env.UPLOAD_BASE_URL; if(process.env.NODE_ENV==='production') throw problem(500,'upload_url_not_configured','Upload base URL is not configured'); return 'http://localhost:9199'; }
app.post('/v1/assets/upload-url',auth,(req,res,next)=>{try{const {fileName,contentType,sizeBytes,purpose}=req.body; if(!['image/jpeg','image/png','image/webp'].includes(contentType)||sizeBytes>10485760) throw problem(400,'invalid_asset','Unsupported image type or size'); const assetId=nanoid(); const objectPath=`users/${res.locals.principal.uid}/uploads/${assetId}-${String(fileName).replace(/[^\w.-]/g,'_')}`; assets.set(assetId,{uid:res.locals.principal.uid,purpose,objectPath,uploaded:false}); res.status(201).json({assetId,uploadUrl:`/v1/assets/upload/${assetId}`,method:'PUT',expiresAt:new Date(Date.now()+10*60_000).toISOString(),objectPath});}catch(e){next(e)}});
app.put('/v1/assets/upload/:assetId',auth,express.raw({type:'*/*',limit:'10mb'}),(req,res,next)=>{try{const asset=assets.get(req.params.assetId); if(!asset||asset.uid!==res.locals.principal.uid) throw problem(404,'asset_not_found','Asset not found'); if(!req.is(['image/jpeg','image/png','image/webp'])) throw problem(400,'invalid_asset','Unsupported image type'); if((req.body as Buffer).byteLength>10485760) throw problem(400,'invalid_asset','Unsupported image size'); assets.set(req.params.assetId,{...asset,uploaded:true}); res.status(200).json({ok:true});}catch(e){next(e)}});
app.post('/v1/generations',auth,(req,res,next)=>{try{const p=res.locals.principal as Principal; const key=req.header('idempotency-key'); if(!key||key.length<8) throw problem(400,'idempotency_key_required','Idempotency-Key header is required'); const idem=`${p.uid}_${key}`; const existing=idempotency.get(idem); if(existing) {log('generation_idempotent_replay',{uid:p.uid,generationId:existing}); return res.json(gens.get(existing));} if(!runtimeState.acceptingSubmissions||runtimeState.killSwitch) throw problem(503,'runtime_paused','Submissions are paused'); const active=[...gens.values()].find(g=>g.uid===p.uid&&['queued','preparing','generating','uploading'].includes(g.status)); if(active) throw problem(409,'active_generation_exists','Only one active generation is allowed'); const {prompt,settings,inputAssets=[]}=req.body; if(!prompt||prompt.length<8||prompt.length>1200) throw problem(400,'invalid_prompt','Prompt must be 8-1200 characters'); for(const a of inputAssets){ if(assets.get(a.assetId)?.uid!==p.uid) throw problem(403,'asset_forbidden','Asset is not owned by caller'); } const cost=calculateCreditCost(settings); const w=wallets.get(p.uid)!; wallets.set(p.uid,reserveCredits(w,cost)); const id=nanoid(); const gen={id,uid:p.uid,prompt,settings,inputAssets,status:'queued' as const,creditCost:cost,createdAt:nowIso(),updatedAt:nowIso(),queuePosition:queue.length+1}; gens.set(id,gen); queue.push({generationId:id,createdAt:gen.createdAt,status:'queued',attempt:0}); runtimeState={...runtimeState,queueDepth:queue.filter(q=>q.status!=='done').length,updatedAt:nowIso()}; idempotency.set(idem,id); log('generation_submitted',{uid:p.uid,generationId:id}); res.status(201).json(gen);}catch(e){next(e)}});
app.get('/v1/generations/:id',auth,(req,res,next)=>{try{const g=gens.get(req.params.id); if(!g||g.uid!==res.locals.principal.uid) throw problem(404,'not_found','Generation not found'); res.json(g);}catch(e){next(e)}});
app.post('/v1/generations/:id/cancel',auth,(req,res,next)=>{try{const g=gens.get(req.params.id); if(!g||g.uid!==res.locals.principal.uid) throw problem(404,'not_found','Generation not found'); if(['completed','failed','cancelled'].includes(g.status)) return res.json(g); if(g.status==='queued'){ wallets.set(g.uid,releaseCredits(wallets.get(g.uid)!,g.creditCost)); } const ng={...g,status:'cancelled' as const,updatedAt:nowIso(),safeErrorMessage:'Cancelled by user'}; gens.set(g.id,ng); const q=queue.find(i=>i.generationId===g.id); if(q) q.status='done'; log('generation_cancelled',{uid:g.uid,generationId:g.id}); res.json(ng);}catch(e){next(e)}});
app.get('/v1/gallery',auth,(req,res)=>{const p=res.locals.principal as Principal; const status=req.query.status; const items=[...gens.values()].filter(g=>g.uid===p.uid&&(!status||g.status===status)).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)); res.json({items:items.slice(0,Number(req.query.limit??20))});});
app.post('/v1/prompts/rewrite',auth,async(req,res,next)=>{try{const {prompt,mode,negativePrompt,enhancePrompt}=req.body??{}; if(!prompt||String(prompt).trim().length<8) throw problem(400,'invalid_prompt','Prompt must be at least 8 characters'); const adapter=runtime as typeof runtime & {rewritePrompt?: (input:{prompt:string;mode?:string;negativePrompt?:string;enhancePrompt?:boolean})=>Promise<{rewrittenPrompt:string}>}; if(typeof adapter.rewritePrompt!=='function') throw problem(503,'runtime_text_model_unavailable','Sulphur text model is not configured'); const out=await adapter.rewritePrompt({prompt:String(prompt).trim(),mode,negativePrompt,enhancePrompt}); return res.json(out); }catch(e){next(e)}});
app.get('/v1/runtime/status',auth,(_req,res)=>res.json({...runtimeState,queueDepth:queue.filter(q=>q.status!=='done').length}));
app.post('/v1/admin/runtime/pause',admin,(_req,res)=>{runtimeState={...runtimeState,acceptingSubmissions:false,status:'paused',updatedAt:nowIso()}; log('admin_runtime_paused'); res.json(runtimeState)});
app.post('/v1/admin/runtime/resume',admin,(_req,res)=>{runtimeState={...runtimeState,acceptingSubmissions:true,killSwitch:false,status:'healthy',updatedAt:nowIso()}; log('admin_runtime_resumed'); res.json(runtimeState)});
app.post('/v1/admin/runtime/stop',admin,(_req,res)=>{runtimeState={...runtimeState,acceptingSubmissions:false,killSwitch:true,status:'unavailable',updatedAt:nowIso()}; log('admin_kill_switch_enabled'); res.json(runtimeState)});
app.post('/v1/admin/credits/adjust',admin,(req,res)=>{const w=wallets.get(req.body.uid)??createWallet(req.body.uid,0); const nw={...w,available:w.available+Number(req.body.amount),updatedAt:nowIso(),version:w.version+1}; wallets.set(req.body.uid,nw); log('admin_credit_adjustment',{uid:req.body.uid,amount:req.body.amount}); res.json(nw)});
export async function processOne(workerId='local-worker'){ const item=claimNext(queue,workerId); if(!item) return; const g=gens.get(item.generationId); if(!g||g.status==='cancelled') { item.status='done'; return; } try{ gens.set(g.id,{...g,status:'preparing',updatedAt:nowIso()}); const sub=await runtime.submitGeneration(g); let st=await runtime.getGenerationStatus(sub.runtimeJobId); while(!['completed','failed','cancelled'].includes(st.state)){ gens.set(g.id,{...gens.get(g.id)!,status:st.state,updatedAt:nowIso(),runtimeJobId:sub.runtimeJobId}); await new Promise(r=>setTimeout(r,60)); st=await runtime.getGenerationStatus(sub.runtimeJobId);} if(st.state==='completed'){ const out=await runtime.fetchOutput(sub.runtimeJobId); wallets.set(g.uid,chargeCredits(wallets.get(g.uid)!,g.creditCost)); gens.set(g.id,{...gens.get(g.id)!,status:'completed',output:{downloadUrl:`/api/v1/generations/${g.id}/download`,durationSeconds:out.durationSeconds},updatedAt:nowIso()}); log('runtime_generation_completed',{generationId:g.id}); } else throw new Error(st.message??st.state); }catch(e){ wallets.set(g.uid,releaseCredits(wallets.get(g.uid)!,g.creditCost)); gens.set(g.id,{...gens.get(g.id)!,status:'failed',safeErrorMessage:'Generation failed safely; credits were returned.',updatedAt:nowIso()}); log('generation_failed',{generationId:g.id}); } finally {item.status='done'; runtimeState={...runtimeState,queueDepth:queue.filter(q=>q.status!=='done').length,updatedAt:nowIso()};}}
app.post('/v1/dev/process-one',auth,async(_req,res)=>{await processOne(); res.json({ok:true})});
app.use((err:unknown,_req:express.Request,res:express.Response,_next:express.NextFunction)=>{const p=typeof err==='object'&&err&&'status'in err?err as ReturnType<typeof problem>:problem(500,'internal_error','Unexpected server error'); res.status(p.status).type('application/problem+json').json(p)});
