import type { VideoSettings } from '@video-lab/contracts';
declare const process: { env: Record<string, string | undefined> };
export interface RuntimeHealth { ok:boolean; provider:string; message?:string }
export interface RuntimeGenerationInput { prompt:string; settings:VideoSettings; inputAssetUrls?:string[] }
export interface RuntimeSubmission { runtimeJobId:string }
export interface RuntimeGenerationStatus { state:'queued'|'preparing'|'generating'|'uploading'|'completed'|'failed'|'cancelled'; progress:number; message?:string|undefined }
export interface RuntimeCancelResult { cancelled:boolean }
export interface RuntimeOutput { bytes:Uint8Array; contentType:'video/mp4'; durationSeconds:number }
export interface VideoRuntimeAdapter { healthCheck():Promise<RuntimeHealth>; submitGeneration(input:RuntimeGenerationInput):Promise<RuntimeSubmission>; getGenerationStatus(runtimeJobId:string):Promise<RuntimeGenerationStatus>; cancelGeneration(runtimeJobId:string):Promise<RuntimeCancelResult>; fetchOutput(runtimeJobId:string):Promise<RuntimeOutput>; }
export class MockVideoRuntimeAdapter implements VideoRuntimeAdapter { private jobs=new Map<string,{created:number;fail?:boolean;cancelled?:boolean}>(); async healthCheck():Promise<RuntimeHealth>{return {ok:true,provider:'mock'};} async submitGeneration(input:RuntimeGenerationInput):Promise<RuntimeSubmission>{ if(input.prompt.includes('[[FAIL_RUNTIME]]')) throw new Error('provider rejection'); const id=`mock_${Date.now()}_${Math.random().toString(16).slice(2)}`; this.jobs.set(id,{created:Date.now(),fail:input.prompt.includes('[[TIMEOUT]]')}); return {runtimeJobId:id}; } async getGenerationStatus(id:string):Promise<RuntimeGenerationStatus>{ const j=this.jobs.get(id); if(!j) return {state:'failed',progress:0,message:'missing mock job'}; if(j.cancelled) return {state:'cancelled',progress:0}; const age=Date.now()-j.created; if(j.fail && age>100) throw new Error('runtime timeout'); if(age<50) return {state:'preparing',progress:15}; if(age<100) return {state:'generating',progress:55}; if(age<150) return {state:'uploading',progress:90}; return {state:'completed',progress:100}; } async cancelGeneration(id:string):Promise<RuntimeCancelResult>{ const j=this.jobs.get(id); if(j) j.cancelled=true; return {cancelled:true}; } async fetchOutput():Promise<RuntimeOutput>{ return {bytes:new TextEncoder().encode('mock mp4 placeholder'),contentType:'video/mp4',durationSeconds:4}; }}
export class SulphurLtxRuntimeAdapter implements VideoRuntimeAdapter { constructor(private cfg:{baseUrl?:string|undefined; token?:string|undefined; healthPath?:string|undefined; timeoutMs?:number|undefined}){} private headers(){return {'content-type':'application/json',authorization:`Bearer ${this.cfg.token}`};} private requireConfig(){ if(!this.cfg.baseUrl||!this.cfg.token) throw new Error('Sulphur runtime is not configured'); } async healthCheck():Promise<RuntimeHealth>{ this.requireConfig(); const res=await fetch(`${this.cfg.baseUrl}${this.cfg.healthPath??'/health'}`,{headers:this.headers()}); return {ok:res.ok,provider:'sulphur-ltx',message:res.statusText}; } async submitGeneration(input:RuntimeGenerationInput):Promise<RuntimeSubmission>{ this.requireConfig(); const res=await fetch(`${this.cfg.baseUrl}/generations`,{method:'POST',headers:this.headers(),body:JSON.stringify({prompt:input.prompt,options:input.settings})}); if(!res.ok) throw new Error('Sulphur submission failed'); const json=await res.json() as {id?:string; jobId?:string}; return {runtimeJobId:json.jobId??json.id??''}; } async getGenerationStatus(runtimeJobId:string):Promise<RuntimeGenerationStatus>{ this.requireConfig(); const res=await fetch(`${this.cfg.baseUrl}/generations/${runtimeJobId}`,{headers:this.headers()}); if(!res.ok) throw new Error('Sulphur status failed'); const j=await res.json() as {status:string; progress?:number; message?:string}; const map:Record<string,RuntimeGenerationStatus['state']>={queued:'queued',preparing:'preparing',running:'generating',generating:'generating',uploading:'uploading',completed:'completed',failed:'failed',cancelled:'cancelled'}; return {state:map[j.status]??'failed',progress:j.progress??0,message:j.message}; } async cancelGeneration(runtimeJobId:string):Promise<RuntimeCancelResult>{ this.requireConfig(); const res=await fetch(`${this.cfg.baseUrl}/generations/${runtimeJobId}/cancel`,{method:'POST',headers:this.headers()}); return {cancelled:res.ok}; } async fetchOutput(runtimeJobId:string):Promise<RuntimeOutput>{ this.requireConfig(); const res=await fetch(`${this.cfg.baseUrl}/generations/${runtimeJobId}/output`,{headers:this.headers()}); if(!res.ok) throw new Error('Sulphur output fetch failed'); return {bytes:new Uint8Array(await res.arrayBuffer()),contentType:'video/mp4',durationSeconds:0}; }}
export function createRuntimeFromEnv(): VideoRuntimeAdapter { return process.env.VIDEO_RUNTIME_PROVIDER==='sulphur-ltx' ? new SulphurLtxRuntimeAdapter({baseUrl:process.env.VIDEO_RUNTIME_BASE_URL,token:process.env.VIDEO_RUNTIME_API_TOKEN,healthPath:process.env.VIDEO_RUNTIME_HEALTH_PATH}) : new MockVideoRuntimeAdapter(); }
